### ISSUE TITLE
2.3系では使えないのでしょうか？

### ISSUE THREAD

**Issue by nakayoshisandayo** [ameya86/redmine_already_read#9]
Environment:
  Redmine version                2.3.4.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2

の環境にインストールしようとすると以下のようなエラーがでてインストールできません。
原因は2.3系だからということでしょうか？

[root@www redmine]# rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
ArgumentError: wrong number of arguments (1 for 0)
/var/lib/redmine/plugins/redmine_already_read-master/lib/already_read/issue_patch.rb:23:in `block in <class:Issue>'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations/builder/collection_association.rb:35:in`[]'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations/builder/collection_association.rb:35:in `wrap_block_extension'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations/builder/collection_association.rb:22:in`build'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/autosave_association.rb:139:in `build'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations/builder/has_many.rb:10:in`build'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations/builder/collection_association.rb:13:in `build'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/associations.rb:1198:in`has_many'
/var/lib/redmine/plugins/redmine_already_read-master/lib/already_read/issue_patch.rb:23:in `<class:Issue>'
/var/lib/redmine/plugins/redmine_already_read-master/lib/already_read/issue_patch.rb:22:in`<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`block in require'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
/var/lib/redmine/plugins/redmine_already_read-master/init.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in`load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/var/lib/redmine/lib/redmine/plugin.rb:130:in`block in load'
/var/lib/redmine/lib/redmine/plugin.rb:121:in `each'
/var/lib/redmine/lib/redmine/plugin.rb:121:in`load'
/var/lib/redmine/config/initializers/30-redmine.rb:12:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in`load'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in`load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/engine.rb:588:in`block (2 levels) in class:Engine'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/engine.rb:587:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/engine.rb:587:in`block in class:Engine'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`run'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:136:in`initialize!'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/lib/redmine/config/environment.rb:14:in`<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:103:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:103:in`require_environment!'
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
[root@www redmine]#

**Comment by ameya86** [comment]
どのバージョンを入れましたか？

v0.0.4は2.3対応していたつもりですが。

v0.0.5は3.x以前では動きません。

**Comment by nakayoshisandayo** [comment]
v0.0.4をインストールしたところ、インストールは問題なくできましたが、
マイページなど既存のチケットが関連するページにアクセスすると以下のような
エラーが出て利用できませんでした。

---

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

**Comment by ameya86** [comment]
CentOS7、ruby1.9.3-p551、MariaDB、Redmine2.3.4の環境にv0.0.4を入れて
いくつかチケット切ってマイページの全項目をオンにして見ましたがエラーになりませんでした。

redmine/log/production.logにエラーメッセージ出たりしていませんか？

**Comment by nakayoshisandayo** [comment]
ログを確認したところ、以下のようなエラーが出ています。

ActionView::Template::Error (undefined method `reflect_on_association' for AlreadyRead:Module):
    9:     </tr></thead>
    10:     <tbody>
    11:     <% for issue in issues %>
    12:     <tr id="issue-<%= h(issue.id) %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %>">
    13:       <td class="id">
    14:         <%= check_box_tag("ids[]", issue.id, false, :style => 'display:none;', :id => nil) %>
    15:         <%= link_to issue.id, issue_path(issue) %>
  app/views/issues/_list_simple.html.erb:12:in`block (2 levels) in _app_views_issues__list_simple_html_erb__2342037617323214119_57708620'
  app/views/issues/_list_simple.html.erb:11:in `each'
  app/views/issues/_list_simple.html.erb:11:in`block in _app_views_issues__list_simple_html_erb__2342037617323214119_57708620'
  app/views/issues/_list_simple.html.erb:2:in `_app_views_issues__list_simple_html_erb__2342037617323214119_57708620'
  app/views/my/blocks/_issuesassignedtome.html.erb:4:in`_app_views_my_blocks__issuesassignedtome_html_erb___1822344875411233865_58680720'
  app/views/my/page.html.erb:11:in `block in _app_views_my_page_html_erb___840302707617373533_58581920'
  app/views/my/page.html.erb:8:in`each'
  app/views/my/page.html.erb:8:in `_app_views_my_page_html_erb___840302707617373533_58581920'

ActionView::Template::Error (undefined method `reflect_on_association' for AlreadyRead:Module):
    28:       </td>
    29:     </tr>
    30:     <% previous_group = group %>
    31:   <% end %>
    32:   <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    33:     <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    34:     <%= raw query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, issue)}</td>"}.join %>
  app/views/issues/_list.html.erb:31:in`block (2 levels) in _app_views_issues__list_html_erb___4542024584247829367_62000180'
  app/helpers/issues_helper.rb:29:in `block in issue_list'
  app/helpers/issues_helper.rb:25:in`each'
  app/helpers/issues_helper.rb:25:in `issue_list'
  app/views/issues/_list.html.erb:18:in`block in _app_views_issues__list_html_erb___4542024584247829367_62000180'
  app/views/issues/_list.html.erb:1:in `_app_views_issues__list_html_erb___4542024584247829367_62000180'
  app/views/issues/index.html.erb:62:in`_app_views_issues_index_html_erb__181280148218430468_58849840'
  app/controllers/issues_controller.rb:83:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:82:in`index'

なお、新しいチケットは発行できるようですが、チケット発行後に発行したチケットを表示する段階で
エラーになります。

以下のようなプラグインを入れていますが、こちらが原因でしょうか？

Redmine plugins:
  redmine_ckeditor               1.0.19
  redmine_menu                   0.1 (20150323)
  redmine_open_links_in_new_window 0.0.3
  redmine_per_project_formatting 0.0.4
  redmine_vividtone_my_page_blocks 1.2 (20120610)

**Comment by ameya86** [comment]
redmine_menuが見つからなかったのでそれ以外を入れてみましたが再現しませんね。
MyPageBlockはなぜかマイページが404になるようになってしまいましたが。

エラーが起きているように見える css_classes はAlreadyReadプラグインで手を加えているので

redmine_already_read/lib/already_read/issue_patch.rb

8行目の

 alias_method_chain :css_classes, :already_read

の先頭に#をつけて無効化すれば

該当箇所のエラーは抑えられるかも知れません。

css_classes はスタイルシート用なので無効化してもプラグインの動作には影響はないはずです。

**Comment by nakayoshisandayo** [comment]
issue_patch.rbの修正を行い、Redmineを再起動したところ、以前はエラーになっていたマイページなどの
チケット一覧ページについては問題なく表示できるようになりました。
ですが、個々のチケットを確認しようとするとエラーになります。
production.logには以下が出力されていました。

NoMethodError (undefined method `reflect_on_association' for AlreadyRead:Module):
  activerecord (3.2.13) lib/active_record/reflection.rb:385:in`block in source_reflection'
  activerecord (3.2.13) lib/active_record/reflection.rb:385:in `collect'
  activerecord (3.2.13) lib/active_record/reflection.rb:385:in`source_reflection'
  activerecord (3.2.13) lib/active_record/reflection.rb:508:in `check_validity!'
  activerecord (3.2.13) lib/active_record/associations/association.rb:26:in`initialize'
  activerecord (3.2.13) lib/active_record/associations/collection_association.rb:24:in `initialize'
  activerecord (3.2.13) lib/active_record/associations/has_many_through_association.rb:10:in`initialize'
  activerecord (3.2.13) lib/active_record/associations.rb:160:in `new'
  activerecord (3.2.13) lib/active_record/associations.rb:160:in`association'
  activerecord (3.2.13) lib/active_record/associations/builder/collection_association.rb:62:in `block in define_readers'
  plugins/redmine_already_read-0.0.4/lib/already_read/issue_patch.rb:34:in`already_read?'
  plugins/redmine_already_read-0.0.4/lib/already_read/issues_controller_patch.rb:9:in `issue_read'
  activesupport (3.2.13) lib/active_support/callbacks.rb:497:in`_run__1893786528469838543__process_action__3765681588511791960__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in`call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.13) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__2128924803537339297__call__3507047295650319185__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in`call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in`method_missing'
  passenger (3.0.15) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:516:in`accept_and_process_next_request'
  passenger (3.0.15) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.15) lib/phusion_passenger/rack/application_spawner.rb:206:in`start_request_handler'
  passenger (3.0.15) lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/utils.rb:470:in`safe_fork'
  passenger (3.0.15) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:180:in`start'
  passenger (3.0.15) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:253:in`block (2 levels) in spawn_rack_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:246:in`block in spawn_rack_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in`synchronize'
  passenger (3.0.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  passenger (3.0.15) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.15) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.15) helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by ameya86** [comment]
原因はプラグインのディレクトリ名のようですね・・・。

自分の環境では「redmine_already_read」にしていたのですが、
上のログに出ているのを見ると「redmine_already_read-0.0.4」になっていますね。
同じ名前にしたら再現しました。

プラグインのディレクトリの名前は「redmine_already_read」でお願いします。

**Comment by nakayoshisandayo** [comment]
そこでしたか。(^^;)
お騒がせしました。解消しました。
